<?php
// module/Album/view/album/album/index.phtml:

$title = $this->translate('Mes albums');
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action'=>'add'));?>"><?php echo $this->translate('Ajouter un album'); ?></a>
</p>

<table class="table">
<tr>
    <th><?php echo $this->translate('Titre'); ?></th>
    <th><?php echo $this->translate('Artiste'); ?></th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($albums as $album) : ?>
<tr>
    <td><?php echo $this->escapeHtml($album->title);?></td>
    <td><?php echo $this->escapeHtml($album->artist);?></td>
    <td>
        <a href="<?php echo $this->url('album',
            array('action'=>'edit', 'id' => $album->id));?>"><?php echo $this->translate('Modifier'); ?></a>
        <a href="<?php echo $this->url('album',
            array('action'=>'delete', 'id' => $album->id));?>"><?php echo $this->translate('Supprimer'); ?></a>
    </td>
</tr>
<?php endforeach; ?>
</table>
